name: video_player_avfoundation
description: iOS implementation of the video_player plugin.
repository: https://github.com/flutter/packages/tree/main/packages/video_player/video_player_avfoundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.4.4
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

flutter:
  plugin:
    implements: video_player
    platforms:
      ios:
        dartPluginClass: AVFoundationVideoPlayer
        pluginClass: FLTVideoPlayerPlugin

dependencies:
  flutter:
    sdk: flutter
  video_player_platform_interface: 
   git:
    url: git@github.com:hungryemon/video_player_platform_interface_mux.git
    ref: 458cf68334b228e66bdd76fae62e18d751338f3c

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^10.0.0
